### ISSUE TITLE
not pictured

### ISSUE THREAD

**Issue by newmesiss** [RevillWeb/angular-preload-image#2]
I am using this great module but can not get it to work.
only shows me the image set in fall , I'm getting data from a REST API , and I think the view is loaded before the data is downloaded and later

``` javascript
<div class="hero slide-up"  preload-bg-image="
{{local.featured_image.attachment_meta.sizes.large.url}}" 
default-image="../img/material-graphite.jpg" 
fallback-image="../img/material3.jpg"></div>
```

controller

```
    $http({
        method: 'GET',
        url: 
    }).
    success(function (data, status, headers, config) {
         $scope.local = data;}
```

**Comment by RevillWeb** [comment]
@newmesiss could you provide an example image URL? You will also need to provide a relative path instead of "../img/material-graphite.jpg" for example.

**Comment by newmesiss** [comment]
I realized that the problem is that the $http.get request is made after the hearing and charged preload is not defined as a route and if not find any images
